name: Build Solo iOS IPA
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install All Required Workloads
        run: |
          dotnet workload install ios android maui

      - name: Publish IPA
        run: |
          dotnet publish OpenUtauMobile/OpenUtauMobile.csproj \
            -f net9.0-ios \
            -r ios-arm64 \
            -c Release \
            -p:ArchiveOnBuild=true \
            -p:SigningIdentity="-" \
            -p:CodesignProvision="-" \
            -p:MtouchExtraArgs="--nowarn:2346"

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenUtauMobile-iOS-IPA
          path: OpenUtauMobile/bin/Release/net9.0-ios/ios-arm64/publish/*.ipa
